### ISSUE TITLE
mvn package requires a texoo.properties file in texoo-core

### ISSUE THREAD

**Issue by Draykee** [sebastianarnold/TeXoo#24]
While executing `mvn package` the "texoo-core\src\test\java\de\datexis\common\PropertiesTest.java" class checks for a version in the "texoo.properties" file.

The master currently just contains a "texoo-core/src/main/resources/texoo.properties.template" file wherefore the test and the build lifecycle fails.

A default "texoo.properties" file needs to be added.

**Comment by sebastianarnold** [comment]
It is intentional that there is no properties file in the repositor, because people would overwrite it wiht htier settings. In texoo-core, we have a [build.xml](https://github.com/sebastianarnold/TeXoo/blob/bf869d0a31218e611cd05fcac079aa91ab81b267/texoo-core/build.xml#L13) which creates a new texoo.properties from the template on first build. This works fine on my machine and in our Jenkins build. Let's figure out why is this not called in your case....

**Comment by sebastianarnold** [comment]
Ok, the script disappeared from the POM after a cleanup, this should be fine again with the next release.
